export const DATA = [
  {
    id: "1",
    date: "2020-11-11T03:23:31.984Z",
    name: "Rowena Jerde",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/a_harris88/128.jpg",
    sold: true,
    price: "51.00",
    brand: "Fantastic Concrete Computer",
    description:
      "You can't copy the capacitor without generating the digital SAS hard drive!",
    seller: "Frederic",
  },
  {
    id: "2",
    date: "2020-11-11T03:25:47.608Z",
    name: "Walter Nicolas",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/uxalex/128.jpg",
    sold: true,
    price: "348.00",
    brand: "Handcrafted Metal Car",
    description:
      "I'll override the open-source HTTP protocol, that should interface the COM program!",
    seller: "Lonnie",
  },
  {
    id: "3",
    date: "2020-11-11T08:07:26.985Z",
    name: "Justina Heaney",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/juangomezw/128.jpg",
    sold: true,
    price: "461.00",
    brand: "Unbranded Frozen Pizza",
    description:
      "Try to synthesize the PNG monitor, maybe it will parse the primary pixel!",
    seller: "Calista",
  },
  {
    id: "4",
    date: "2020-11-10T17:50:08.753Z",
    name: "Mrs. Elizabeth Tremblay",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/operatino/128.jpg",
    sold: false,
    price: "71.00",
    brand: "Handcrafted Rubber Chair",
    description:
      "overriding the transmitter won't do anything, we need to back up the primary HTTP driver!",
    seller: "Kirk",
  },
  {
    id: "5",
    date: "2020-11-10T19:24:15.382Z",
    name: "D'angelo Douglas",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/jffgrdnr/128.jpg",
    sold: false,
    price: "465.00",
    brand: "Handmade Fresh Gloves",
    description:
      "generating the circuit won't do anything, we need to synthesize the primary ADP monitor!",
    seller: "Citlalli",
  },
  {
    id: "6",
    date: "2020-11-11T14:12:11.469Z",
    name: "Ms. Bonnie Leffler",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/bobwassermann/128.jpg",
    sold: false,
    price: "943.00",
    brand: "Awesome Fresh Bike",
    description:
      "The AGP circuit is down, navigate the primary panel so we can program the RAM firewall!",
    seller: "Araceli",
  },
  {
    id: "7",
    date: "2020-11-11T15:19:29.728Z",
    name: "Dr. Jason Block",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/nilshoenson/128.jpg",
    sold: false,
    price: "847.00",
    brand: "Generic Soft Cheese",
    description:
      "I'll program the cross-platform HDD firewall, that should system the TCP monitor!",
    seller: "Allan",
  },
  {
    id: "8",
    date: "2020-11-11T01:29:04.277Z",
    name: "Cesar Donnelly Jr.",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/kazaky999/128.jpg",
    sold: false,
    price: "63.00",
    brand: "Ergonomic Soft Shoes",
    description:
      "You can't quantify the pixel without bypassing the cross-platform PNG application!",
    seller: "Kaylah",
  },
  {
    id: "9",
    date: "2020-11-11T05:52:34.993Z",
    name: "Elva Sauer",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/dorphern/128.jpg",
    sold: false,
    price: "461.00",
    brand: "Incredible Metal Bacon",
    description:
      "The XML application is down, calculate the neural hard drive so we can compress the SQL hard drive!",
    seller: "Wilburn",
  },
  {
    id: "10",
    date: "2020-11-11T06:49:34.035Z",
    name: "Vincenza Jerde",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/judzhin_miles/128.jpg",
    sold: false,
    price: "147.00",
    brand: "Incredible Frozen Mouse",
    description:
      "If we override the monitor, we can get to the AGP pixel through the virtual HDD card!",
    seller: "Horace",
  },
  {
    id: "11",
    date: "2020-11-10T17:34:51.267Z",
    name: "Meredith Altenwerth",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/derekebradley/128.jpg",
    sold: false,
    price: "377.00",
    brand: "Licensed Rubber Pants",
    description:
      "backing up the system won't do anything, we need to back up the virtual PNG firewall!",
    seller: "Kip",
  },
  {
    id: "12",
    date: "2020-11-11T14:57:38.216Z",
    name: "Jessica Grant DVM",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/terpimost/128.jpg",
    sold: false,
    price: "298.00",
    brand: "Rustic Granite Chicken",
    description:
      "Use the mobile THX monitor, then you can compress the solid state interface!",
    seller: "Nestor",
  },
  {
    id: "13",
    date: "2020-11-11T13:05:28.042Z",
    name: "Miss Jerald Schmidt",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/prrstn/128.jpg",
    sold: false,
    price: "545.00",
    brand: "Handmade Rubber Pizza",
    description:
      "Try to program the SCSI interface, maybe it will reboot the auxiliary driver!",
    seller: "Kasandra",
  },
  {
    id: "14",
    date: "2020-11-11T03:19:21.636Z",
    name: "Agustin Bins",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/giuliusa/128.jpg",
    sold: false,
    price: "898.00",
    brand: "Small Frozen Chicken",
    description:
      "synthesizing the port won't do anything, we need to input the optical IB array!",
    seller: "Coleman",
  },
  {
    id: "15",
    date: "2020-11-11T09:53:41.341Z",
    name: "Greyson Towne",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/pyronite/128.jpg",
    sold: false,
    price: "922.00",
    brand: "Awesome Rubber Chips",
    description:
      "connecting the monitor won't do anything, we need to hack the optical AI transmitter!",
    seller: "Johnnie",
  },
  {
    id: "16",
    date: "2020-11-11T14:34:05.792Z",
    name: "Tierra Kuhic",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/xadhix/128.jpg",
    sold: false,
    price: "957.00",
    brand: "Ergonomic Wooden Gloves",
    description:
      "Use the open-source SCSI protocol, then you can copy the neural alarm!",
    seller: "Rodrick",
  },
  {
    id: "17",
    date: "2020-11-10T16:20:36.767Z",
    name: "Mr. Mitchell Mueller",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/ffbel/128.jpg",
    sold: false,
    price: "76.00",
    brand: "Licensed Steel Chair",
    description:
      "synthesizing the firewall won't do anything, we need to calculate the digital SSL pixel!",
    seller: "Noble",
  },
  {
    id: "18",
    date: "2020-11-11T00:18:21.508Z",
    name: "Bonnie Kemmer III",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/mashaaaaal/128.jpg",
    sold: false,
    price: "208.00",
    brand: "Unbranded Concrete Ball",
    description:
      "Use the multi-byte JSON pixel, then you can program the redundant panel!",
    seller: "Giuseppe",
  },
  {
    id: "19",
    date: "2020-11-10T22:35:52.364Z",
    name: "Danyka Koepp",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/aiiaiiaii/128.jpg",
    sold: false,
    price: "349.00",
    brand: "Practical Cotton Gloves",
    description:
      "The JBOD card is down, hack the optical panel so we can bypass the FTP bandwidth!",
    seller: "Kory",
  },
  {
    id: "20",
    date: "2020-11-10T23:04:16.321Z",
    name: "Serenity Hane Sr.",
    img: "https://s3.amazonaws.com/uifaces/faces/twitter/oktayelipek/128.jpg",
    sold: false,
    price: "201.00",
    brand: "Unbranded Metal Car",
    description:
      "You can't reboot the card without backing up the cross-platform EXE bus!",
    seller: "Allene",
  },
];
